<?php

namespace PIDEV\UserBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArray($array)
    {
      $qb = $this->createQueryBuilder('u')
          ->select('u')
          ->where('u.id IN(:array)')
          ->setParameter('array',$array);
      return $qb->getQuery()->getResult();
    }
    public function findProduit($p)
    {
        $query=$this->getEntityManager()->createQuery(
        // "select m from MyAppParcBundle:Marque m WHERE m.libelle LIKE :p")->setParameter('p','%'.$p.'%');
            "select m from PIDEVUserBundle:Produit m WHERE m.nomP LIKE :p OR m.categorie LIKE :p")->
        setParameter('p','%'.$p.'%');
        return $query->getResult();

    }

    public function ByCategorie($categorie)
    {
        $req=$this->createQueryBuilder('u')
            ->select('u')
            ->where('u.categorie = : categorie')
            ->orderBy('u.categorie', 'DESC')->
           setParameter('categorie','%'.$categorie.'%');
        return $req->getQuery()->getResult();
    }
    public function ByCat($categorie)
    {
        $query=$this->getEntityManager()->createQuery(
        // "select m from MyAppParcBundle:Marque m WHERE m.libelle LIKE :p")->setParameter('p','%'.$p.'%');
            'select m from PIDEVUserBundle:Produit m WHERE IDENTITY (m.categorie) like :categorie')->
        setParameter('categorie','%'.$categorie.'%');
        return $query->getResult();

    }

    public function Cat()
    {
        $query=$this->getEntityManager()->createQuery(
        // "select m from MyAppParcBundle:Marque m WHERE m.libelle LIKE :p")->setParameter('p','%'.$p.'%');
            "select m from PIDEVUserBundle:Produit m ")
        ;
        return $query->getResult();

    }


}
