<?php

namespace PIDEV\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function findProduit($p)
    {
        $query=$this->getEntityManager()->createQuery(
        // "select m from MyAppParcBundle:Marque m WHERE m.libelle LIKE :p")->setParameter('p','%'.$p.'%');
            "select m from PIDEVUserBundle:Produit m WHERE m.nomP LIKE :p OR m.categorie LIKE :p")->
        setParameter('p','%'.$p.'%');
        return $query->getResult();

    }
}
